import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { AlertTriangle, FileText, Target, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiGet } from "@/lib/api";

type StudentRow = { student_id: string; name: string; assessment: string; score: number; gap: string | null; concept_cleared_percentage: number; mastery: number | null; submitted_at: string };
type Response = { students: StudentRow[] };

export default function TeacherStudentDashboardView() {
  const query = useQuery({ queryKey: ["teacher-student-dashboard"], queryFn: () => apiGet<Response>("/teacher/student-dashboard"), retry: 1 });
  return <div data-testid="teacher-student-dashboard" className="animate-rise-in">
    <div className="mb-7"><p className="mb-2 font-mono text-[11px] uppercase tracking-[0.2em] text-blue-600">Teacher workspace / Live evidence</p><h1 className="font-heading text-3xl font-bold tracking-tight text-slate-900">Student Dashboard</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Students who have submitted classroom assessments, with their latest real score, learning gap and concept recovery evidence.</p></div>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Tests submitted" value={query.data ? String(query.data.students.length) : "—"} icon={<FileText size={17} />} /><Metric label="Students shown" value={query.data ? String(new Set(query.data.students.map((s) => s.student_id)).size) : "—"} icon={<Users size={17} />} /><Metric label="Needs attention" value={query.data ? String(query.data.students.filter((s) => s.gap).length) : "—"} icon={<AlertTriangle size={17} />} /><Metric label="Cleared concepts" value={query.data?.students.length ? Math.round(query.data.students.reduce((sum, s) => sum + s.concept_cleared_percentage, 0) / query.data.students.length) + "%" : "—"} icon={<Target size={17} />} /></div>
    <Card className="border-[#E2D9CE]"><CardHeader className="border-b border-[#E2D9CE]"><CardTitle className="font-heading text-xl">Assessment results</CardTitle><p className="text-sm text-slate-500">Only persisted assessment submissions are shown.</p></CardHeader><CardContent className="p-5">{query.data?.students.length ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-400"><th className="px-3 py-3">Student</th><th className="px-3 py-3">Test</th><th className="px-3 py-3">Score</th><th className="px-3 py-3">Learning gap</th><th className="px-3 py-3">Concepts cleared</th><th className="px-3 py-3">Mastery</th></tr></thead><tbody>{query.data.students.map((student) => <tr key={student.student_id + "-" + student.submitted_at} className="border-b border-slate-100 last:border-0"><td className="px-3 py-4 font-medium text-slate-800">{student.name}</td><td className="px-3 py-4 text-slate-600">{student.assessment}</td><td className="px-3 py-4"><Badge variant="outline">{Math.round(student.score * 100)}%</Badge></td><td className="px-3 py-4">{student.gap ? <Badge className="border-0 bg-rose-50 text-rose-700">{student.gap.replaceAll("_", " ")}</Badge> : <span className="text-emerald-700">No active gap</span>}</td><td className="px-3 py-4 font-mono text-slate-700">{student.concept_cleared_percentage}%</td><td className="px-3 py-4 font-mono text-slate-700">{student.mastery === null ? "—" : Math.round(student.mastery * 100) + "%"}</td></tr>)}</tbody></table></div> : <div className="rounded-xl border border-dashed border-slate-200 p-10 text-center text-sm text-slate-500">{query.isLoading ? "Loading live assessment data…" : "No students have submitted an assessment yet."}</div>}</CardContent></Card>
  </div>;
}
function Metric({ label, value, icon }: { label: string; value: string; icon: ReactNode }) { return <div className="rounded-2xl border border-[#E2D9CE] bg-white p-4"><div className="flex items-center justify-between text-blue-600">{icon}<span className="font-mono text-[10px] uppercase tracking-wider text-slate-400">Live</span></div><p className="mt-4 text-xs text-slate-500">{label}</p><p className="mt-1 font-heading text-2xl font-bold text-slate-900">{value}</p></div>; }
