import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Eye, FilePlus2, FileText, Folder, FolderPlus, HardDrive, Heart, Pencil, Search, Star, Trash2, UploadCloud } from "lucide-react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiDelete, apiGet, apiPatch, apiPost, apiUpload } from "@/lib/api";
import type { LibraryFolder, LibraryItem, StorageStatus, User } from "@/lib/types";

const formatBytes = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;

export default function LibraryView({ user }: { user: User }) {
  const queryClient = useQueryClient();
  const fileRef = useRef<HTMLInputElement>(null);
  const imageRef = useRef<HTMLInputElement>(null);
  const folderRef = useRef<HTMLInputElement>(null);
  const [search, setSearch] = useState("");
  const [folderId, setFolderId] = useState<string | null>(null);
  const [folderName, setFolderName] = useState("");
  const [noteOpen, setNoteOpen] = useState(false);
  const [noteName, setNoteName] = useState("");
  const [noteContent, setNoteContent] = useState("");
  const [preview, setPreview] = useState<LibraryItem | null>(null);

  const storage = useQuery({ queryKey: ["library-storage"], queryFn: () => apiGet<StorageStatus>("/library/storage") });
  const folders = useQuery({ queryKey: ["library-folders"], queryFn: () => apiGet<LibraryFolder[]>("/library/folders") });
  const items = useQuery({ queryKey: ["library-items", search, folderId], queryFn: () => apiGet<LibraryItem[]>(`/library/items?search=${encodeURIComponent(search)}${folderId ? `&folder_id=${folderId}` : ""}`) });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ["library-items"] }); void queryClient.invalidateQueries({ queryKey: ["library-storage"] }); };

  const createFolder = useMutation({ mutationFn: () => apiPost<LibraryFolder>("/library/folders", { name: folderName, parent_id: null }), onSuccess: () => { setFolderName(""); void queryClient.invalidateQueries({ queryKey: ["library-folders"] }); }, onError: () => toast.error("Folder could not be created.") });
  const createNote = useMutation({ mutationFn: () => apiPost<LibraryItem>("/library/notes", { name: noteName, content: noteContent, folder_id: folderId }), onSuccess: () => { setNoteName(""); setNoteContent(""); setNoteOpen(false); refresh(); }, onError: () => toast.error("Note could not be saved.") });
  const updateItem = useMutation({ mutationFn: ({ id, values }: { id: string; values: Record<string, unknown> }) => apiPatch<LibraryItem>(`/library/items/${id}`, values), onSuccess: refresh, onError: () => toast.error("Library item could not be updated.") });
  const deleteItem = useMutation({ mutationFn: (id: string) => apiDelete<void>(`/library/items/${id}`), onSuccess: () => { setPreview(null); refresh(); }, onError: () => toast.error("Library item could not be deleted.") });
  const upload = useMutation({ mutationFn: (file: File) => { const data = new FormData(); data.append("file", file); return apiUpload<LibraryItem>(`/library/upload${folderId ? `?folder_id=${folderId}` : ""}`, data); }, onSuccess: refresh, onError: () => toast.error("Upload failed. Check the storage connection and file type.") });
  const uploadMany = async (files: FileList | File[]) => {
    const selected = Array.from(files);
    if (!selected.length) return;
    if (!storage.data?.enabled) { toast.error("Storage is disabled. Connect storage before uploading."); return; }
    for (const file of selected) await upload.mutateAsync(file);
    refresh();
  };

  const used = storage.data?.used_bytes ?? 0;
  const limit = storage.data?.limit_bytes ?? 500 * 1024 * 1024;
  const selectedFolder = folders.data?.find((folder) => folder.id === folderId);

  return <div data-testid="library-view" className="relative animate-rise-in overflow-hidden rounded-[28px] bg-gradient-to-br from-white via-blue-50/30 to-indigo-50/50 p-1"><div className="relative rounded-[24px] bg-white/80 p-4 sm:p-6 lg:p-7 backdrop-blur-sm">
    <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 font-mono text-[11px] uppercase tracking-[0.2em] text-blue-600">Personal workspace / Private</p><h1 data-testid="library-title" className="font-heading text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">Your Library.</h1><p data-testid="library-description" className="mt-3 max-w-2xl leading-7 text-slate-600">Stores your private notes and study resources so you can organize, preview, and use them throughout your personalized learning workflow.</p></div><div className="flex flex-wrap gap-2">
      <Button data-testid="create-note-button" variant="outline" onClick={() => setNoteOpen((value) => !value)}><FilePlus2 size={16} /> New note</Button>
      <Button data-testid="upload-file-button" variant="outline" onClick={() => fileRef.current?.click()} disabled={!storage.data?.enabled || upload.isPending}><UploadCloud size={16} /> Browse files</Button>
      <Button data-testid="browse-document-button" variant="outline" onClick={() => fileRef.current?.click()} disabled={!storage.data?.enabled || upload.isPending}><FileText size={16} /> Document</Button>
      <Button data-testid="browse-image-button" variant="outline" onClick={() => imageRef.current?.click()} disabled={!storage.data?.enabled || upload.isPending}><Eye size={16} /> Image</Button>
      <Button data-testid="browse-folder-button" variant="outline" onClick={() => folderRef.current?.click()} disabled={!storage.data?.enabled || upload.isPending}><Folder size={16} /> Folder</Button>
      <input data-testid="library-file-input" ref={fileRef} type="file" className="hidden" multiple accept=".pdf,.png,.jpg,.jpeg,.gif,.webp,.ppt,.pptx,.doc,.docx,.txt,.md,.csv" onChange={(event) => { if (event.target.files) void uploadMany(event.target.files); event.currentTarget.value = ""; }} />
      <input data-testid="library-image-input" ref={imageRef} type="file" className="hidden" multiple accept="image/*" onChange={(event) => { if (event.target.files) void uploadMany(event.target.files); event.currentTarget.value = ""; }} />
      <input data-testid="library-folder-input" ref={folderRef} type="file" className="hidden" multiple {...({ webkitdirectory: "", directory: "" } as Record<string, string>)} onChange={(event) => { if (event.target.files) void uploadMany(event.target.files); event.currentTarget.value = ""; }} />
    </div></div>

    <Card data-testid="storage-status-card" className={`mb-6 border-0 bg-gradient-to-r ${storage.data?.enabled ? "from-emerald-50 to-blue-50" : "from-amber-50 to-blue-50"} shadow-sm ring-1 ring-slate-200/70`}><CardContent className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><HardDrive className={storage.data?.enabled ? "text-emerald-700" : "text-amber-700"} size={21} /><div><div className="flex flex-wrap items-center gap-2"><p data-testid="storage-provider" className="font-heading font-semibold text-slate-900">Emergent File & Media Storage</p><Badge data-testid="storage-connection-badge" variant="outline" className={storage.data?.enabled ? "border-emerald-200 bg-white text-emerald-700" : "border-amber-200 bg-white text-amber-700"}>{storage.data?.enabled ? "Connected" : "Disabled"}</Badge></div><p data-testid="storage-message" className="mt-1 text-sm leading-6 text-slate-600">{storage.data?.message ?? "Checking storage…"}</p></div></div><div className="min-w-48"><div className="mb-2 flex justify-between font-mono text-xs text-slate-500"><span>{formatBytes(used)}</span><span>500 MB</span></div><div className="h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, (used / limit) * 100)}%` }} /></div></div></div></CardContent></Card>

    {noteOpen ? <Card data-testid="new-note-form" className="mb-6 border-blue-200 bg-blue-50/50"><CardContent className="grid gap-4 p-5"><div><Label htmlFor="note-name">Note name</Label><Input id="note-name" data-testid="note-name-input" className="mt-2 bg-white" value={noteName} onChange={(event) => setNoteName(event.target.value)} /></div><div><Label htmlFor="note-content">Note</Label><Textarea id="note-content" data-testid="note-content-input" className="mt-2 min-h-28 bg-white" value={noteContent} onChange={(event) => setNoteContent(event.target.value)} /></div><div className="flex gap-2"><Button data-testid="save-note-button" onClick={() => createNote.mutate()} disabled={!noteName.trim() || !noteContent.trim() || createNote.isPending}>Save note</Button><Button data-testid="cancel-note-button" variant="ghost" onClick={() => setNoteOpen(false)}>Cancel</Button></div></CardContent></Card> : null}

    <div className="grid gap-6 xl:grid-cols-[240px_1fr]">
      <Card data-testid="library-folders-card" className="h-fit border-0 bg-gradient-to-b from-white to-blue-50/40 shadow-sm ring-1 ring-slate-200/80"><CardHeader><CardTitle className="flex items-center gap-2 font-heading text-lg text-slate-900"><Folder size={18} /> Folders</CardTitle></CardHeader><CardContent><button data-testid="folder-all-button" onClick={() => setFolderId(null)} className={`w-full rounded-lg px-3 py-2 text-left text-sm ${folderId === null ? "bg-blue-50 font-medium text-blue-700" : "text-slate-600 hover:bg-slate-50"}`}>All files</button>{folders.data?.map((folder) => <button key={folder.id} data-testid={`folder-button-${folder.id}`} onClick={() => setFolderId(folder.id)} className={`mt-1 w-full rounded-lg px-3 py-2 text-left text-sm ${folderId === folder.id ? "bg-blue-50 font-medium text-blue-700" : "text-slate-600 hover:bg-slate-50"}`}>{folder.name}</button>)}<div className="mt-4 flex gap-2 border-t border-[#E2D9CE] pt-4"><Input data-testid="new-folder-name-input" aria-label="New folder name" value={folderName} onChange={(event) => setFolderName(event.target.value)} placeholder="New folder" /><Button data-testid="create-folder-button" size="icon" aria-label="Create folder" disabled={!folderName.trim()} onClick={() => createFolder.mutate()}><FolderPlus size={16} /></Button></div></CardContent></Card>
      <div><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-md flex-1"><Search size={16} className="absolute left-3 top-2.5 text-slate-400" /><Input data-testid="library-search-input" aria-label="Search Library" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search files and notes" className="pl-9" /></div><p data-testid="library-location" className="text-sm text-slate-500">{selectedFolder ? selectedFolder.name : "All files"} · {items.data?.length ?? 0} items</p></div>
        <div className="grid gap-3 md:grid-cols-2">{items.data?.map((item) => <Card key={item.id} data-testid={`library-item-${item.id}`} className="border-0 bg-gradient-to-br from-white to-blue-50/35 shadow-sm ring-1 ring-slate-200/80 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-4"><div className="flex items-start gap-3"><div className="rounded-xl bg-gradient-to-br from-blue-100 to-indigo-100 p-2 text-blue-700">{item.kind === "note" ? <FileText size={18} /> : <FilePlus2 size={18} />}</div><div className="min-w-0 flex-1"><p data-testid={`library-item-name-${item.id}`} className="truncate font-medium text-slate-800">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.kind === "note" ? "Note" : item.content_type} · {formatBytes(item.size)}</p>{item.retrieval_status === "ready_for_future_retrieval" ? <Badge className="mt-2 bg-emerald-50 text-emerald-700">Ready for future retrieval</Badge> : null}</div>{item.favorite ? <Star size={16} className="fill-amber-400 text-amber-400" /> : null}</div><div className="mt-4 flex flex-wrap gap-1 border-t border-[#E2D9CE] pt-3"><Button data-testid={`preview-item-${item.id}`} variant="ghost" size="icon-sm" aria-label={`Preview ${item.name}`} onClick={() => setPreview(item)}><Eye size={15} /></Button><Button data-testid={`download-item-${item.id}`} variant="ghost" size="icon-sm" aria-label={`Download ${item.name}`} onClick={() => window.open(`/api/library/items/${item.id}/download`, "_blank")}><Download size={15} /></Button><Button data-testid={`favorite-item-${item.id}`} variant="ghost" size="icon-sm" aria-label={`Favourite ${item.name}`} onClick={() => updateItem.mutate({ id: item.id, values: { favorite: !item.favorite } })}><Heart size={15} /></Button><Button data-testid={`rename-item-${item.id}`} variant="ghost" size="icon-sm" aria-label={`Rename ${item.name}`} onClick={() => { const name = window.prompt("Rename item", item.name); if (name?.trim()) updateItem.mutate({ id: item.id, values: { name: name.trim() } }); }}><Pencil size={15} /></Button><Button data-testid={`delete-item-${item.id}`} variant="ghost" size="icon-sm" aria-label={`Delete ${item.name}`} className="text-rose-600" onClick={() => { if (window.confirm(`Delete ${item.name}?`)) deleteItem.mutate(item.id); }}><Trash2 size={15} /></Button></div></CardContent></Card>)}{!items.isLoading && !items.data?.length ? <Card data-testid="library-empty-state" className="col-span-full border-dashed border-[#E2D9CE] bg-white/60"><CardContent className="flex flex-col items-center p-10 text-center"><Folder className="text-slate-300" size={30} /><p className="mt-4 font-heading font-semibold text-slate-800">This folder is empty</p><p className="mt-1 text-sm text-slate-500">Create a note now, or connect storage later to upload study files.</p></CardContent></Card> : null}</div>
      </div>
    </div>
    {preview ? <div data-testid="library-preview-panel" className="fixed inset-0 z-40 flex items-end justify-center bg-black/25 p-4 backdrop-blur-sm sm:items-center" onMouseDown={(event) => { if (event.target === event.currentTarget) setPreview(null); }}><Card className="max-h-[80svh] w-full max-w-2xl overflow-auto border-[#E2D9CE]"><CardHeader className="border-b border-[#E2D9CE]"><div className="flex items-center justify-between gap-3"><CardTitle className="truncate font-heading text-xl">{preview.name}</CardTitle><Button data-testid="close-preview-button" variant="ghost" onClick={() => setPreview(null)}>Close</Button></div></CardHeader><CardContent className="p-6">{preview.kind === "note" ? <pre data-testid="note-preview-content" className="whitespace-pre-wrap font-sans text-sm leading-7 text-slate-700">{preview.content}</pre> : preview.content_type.startsWith("image/") ? <img data-testid="image-preview" src={`/api/library/items/${preview.id}/download`} alt={preview.name} className="max-h-[60svh] w-full object-contain" /> : preview.content_type === "application/pdf" ? <iframe data-testid="pdf-preview" src={`/api/library/items/${preview.id}/download`} title={preview.name} className="h-[60svh] w-full" /> : <p className="text-sm text-slate-600">Preview is not available for this file type. Download it to open in the appropriate application.</p>}</CardContent></Card></div> : null}
  </div></div>;
}